version: "2"

linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    gocyclo:
      min-complexity: 30
    misspell:
      locale: US

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - gosec
    paths:
      - vendor
      - third_party
