on:
  push:
    branches:
      - main
      - master
      - nftables
  pull_request:
name: test
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.25.5"]
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Run Revive Action by pulling pre-built image
      uses: docker://morphy/revive-action:v2
      with:
        exclude: "./vendor/..."

    - name: Run go fmt
      run: diff -u <(echo -n) <(gofmt -d -s ./cmd/ ./pkg/)

    - name: Run go vet
      run: go vet ./...

    - name: Run go env toolchain
      run: go env -w GOTOOLCHAIN=go${{ matrix.go-version }}+auto


    - name: Load kernel modules
      run: sudo modprobe nft_ct

    - name: Test
      run: |
        sudo go test -v -coverprofile=profile.cov ./...
        sudo chown $(id -u):$(id -g) profile.cov

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      continue-on-error: true
      with:
        path-to-profile: profile.cov
        flag-name: "Go-${{ matrix.go-version }}-${{ matrix.os }}"
        parallel: true

  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        continue-on-error: true
        with:
          parallel-finished: true
